### ISSUE TITLE
MH not really working after D2R update

### ISSUE THREAD

**Issue by jan3k** [joffreybesos/d2r-mapview#24]
After today's D2R update the d2map(2.7.9) doesnt show the exposed map.

**Comment by JohnPolansky** [comment]
Found this in the logs if it helps:
```
2022-04-27 14-30-32: DEBUG: Did not find a player offset in unit hashtable, likely in game menu.
2022-04-27 14-30-32: DEBUG: Offset attempts 26
2022-04-27 14-30-32: DEBUG: Scanning for new player offset address, starting default offset -1596669013
```

**Comment by Spink2019** [comment]
Same experience. Not revealing the map.

**Comment by joffreybesos** [comment]
There is a beta release which addresses this issue.
At the moment you must start an offline game with _any_ offline character. Then exit that game, then you can start a new online game as normal. The maphack will work then.
https://github.com/joffreybesos/d2r-mapview/releases/tag/v2.8.0-BETA

This will likely be fixed in a future release
